### PR TITLE
One fix to rule them all

### LINKED ISSUE #10: Create bindings for Fortran
It should be easy using the **C** interface.

### PR DESCRIPTION
**Pull request by newlawrence**
This pull request finally fixes #10. More info in the following line notes.

### CODE REVIEW

File: include/calculate/c-interface.h [hunk 1]
```diff
@@ -1,8 +1,17 @@
 #ifndef __CALCULATE_C_INTERFACE_H__
 #define __CALCULATE_C_INTERFACE_H__
 
+#ifdef _MSC_VER
+#define EXPORT_GLOBAL __declspec(dllimport)
```
Comment (newlawrence) [inline include/calculate/c-interface.h:5]: The `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` [only works for methods](https://cmake.org/cmake/help/v3.4/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html), shared libraries under **Windows** were failing at linking because of this. The only solution is to add the `__declspec(dllimport)` directive when using **MSVC** compiler.

File: binding/fortran/source/calculate.f90 [hunk 2]
```diff
@@ -184,10 +193,12 @@ subroutine assignExpression(this, other)
         class(Expression), intent(inout) :: this
         type(Expression), intent(in) :: other
 
+        type(LibraryTemplate), pointer :: Calculate
         procedure(newExpressionWrapper), pointer :: new
 
         if (other%init_number == MAGIC_NUMBER) then
-            call c_f_procpointer(CalculateLibrary%newExpression, new)
+            call c_f_pointer(libraryReference(), Calculate)
```
Comment (newlawrence) [inline binding/fortran/source/calculate.f90:200]: **Fortran** compilers ignore extern globals as a requirement, so the linker didn't link against them returning arbitrary memory locations. The solution was to define a function that returns a reference to the library, as the linker can't link against undefined methods.
